########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Description:
  This template creates a custom resource Lambda to deploy OIDC Provider and GitHub Actions Role within an AWS Organization - 'github-oidc'
  solution in the repo, https://github.com/aws-samples/aws-security-reference-architecture-examples (sra-1ssgnse6b)

Metadata:
  SRA:
    Version: 1.0
    Entry: Parameters for deploying the solution resolving SSM parameters
    Order: 1
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Properties
        Parameters:
          - pSRASolutionName
          - pSRASolutionVersion
          - pSRAStagingS3BucketName

      - Label:
          default: GitHub OIDC Configuration Properties
        Parameters:
          - pGitHubOrganization
          - pGitHubRepository
          - pMaxSessionDuration

    ParameterLabels:
      pGitHubOrganization:
        default: GitHub Organization
      pGitHubRepository:
        default: GitHub Repository
      pMaxSessionDuration:
        default: Max Session Duration
      pSRASolutionName:
        default: SRA Solution Name
      pSRASolutionVersion:
        default: SRA Solution Version
      pSRAStagingS3BucketName:
        default: SRA Staging S3 Bucket Name

Parameters:
  pRootOrganizationalUnitId:
    AllowedPattern: '^([\w.-]{1,900})$|^(\/[\w.-]{1,900})*[\w.-]{1,900}$'
    ConstraintDescription:
      Must be alphanumeric or special characters [., _, -]. In addition, the slash character ( / ) used to delineate hierarchies in parameter names.
    Default: /sra/control-tower/root-organizational-unit-id
    Description: SSM Parameter for Root Organizational Unit ID
    Type: AWS::SSM::Parameter::Value<String>
  pGitHubOrganization:
    AllowedPattern: '^[a-zA-Z0-9-]+$'
    ConstraintDescription: Must contain only alphanumeric characters and hyphens
    Description: GitHub organization name
    Type: String
  pGitHubRepository:
    AllowedPattern: '^[a-zA-Z0-9-_.]+$'
    ConstraintDescription: Must contain only alphanumeric characters, hyphens, underscores, and dots
    Description: GitHub repository name
    Type: String
  pMaxSessionDuration:
    ConstraintDescription: Max Session Duration must be a number between 900 and 43200, inclusive.
    Default: 3600
    Description: Maximum session duration in seconds
    MinValue: 900
    MaxValue: 43200
    Type: Number
  pSRASolutionName:
    AllowedValues: [sra-github-oidc]
    Default: sra-github-oidc
    Description: The SRA solution name. The default value is the folder name of the solution
    Type: String
  pSRAStagingS3BucketName:
    AllowedPattern: '^([\w.-]{1,900})$|^(\/[\w.-]{1,900})*[\w.-]{1,900}$'
    ConstraintDescription:
      Must be alphanumeric or special characters [., _, -]. In addition, the slash character ( / ) used to delineate hierarchies in parameter names.
    Default: /sra/staging-s3-bucket-name
    Description:
      SSM Parameter for SRA Staging S3 bucket name for the artifacts relevant to solution. (e.g., lambda zips, CloudFormation templates) S3 bucket
      name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Type: AWS::SSM::Parameter::Value<String>
  pSRASolutionVersion:
    AllowedValues: [v1.0]
    Default: v1.0
    Description: The SRA solution version. Used to trigger updates on the nested StackSets.
    Type: String

Conditions:
  cNotGlobalRegionUsEast1: !Not [!Equals [!Ref 'AWS::Region', us-east-1]]

Resources:
  # OIDC Stack for current account
  rGitHubOIDCStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub https://${pSRAStagingS3BucketName}.s3.${AWS::Region}.${AWS::URLSuffix}/${pSRASolutionName}/templates/sra-github-oidc-oidc.yaml
      Parameters:
        pGitHubOrganization: !Ref pGitHubOrganization
        pGitHubRepository: !Ref pGitHubRepository
        pMaxSessionDuration: !Ref pMaxSessionDuration
        pSRASolutionName: !Ref pSRASolutionName
      Tags:
        - Key: sra-solution
          Value: !Ref pSRASolutionName

  # OIDC StackSet for multiple accounts
  rGitHubOIDCStackSet:
    Type: AWS::CloudFormation::StackSet
    DependsOn: rGitHubOIDCStack
    Properties:
      StackSetName: sra-github-oidc-stackset
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      CallAs: SELF
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Description: !Sub ${pSRASolutionVersion} - Deploys OIDC Provider and GitHub Actions Role via ${pSRASolutionName}
      ManagedExecution:
        Active: true
      OperationPreferences:
        FailureTolerancePercentage: 100
        MaxConcurrentPercentage: 100
        RegionConcurrencyType: PARALLEL
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref pRootOrganizationalUnitId
          Regions:
            - !Ref AWS::Region
      TemplateURL: !Sub https://${pSRAStagingS3BucketName}.s3.${AWS::Region}.${AWS::URLSuffix}/${pSRASolutionName}/templates/sra-github-oidc-oidc.yaml
      Parameters:
        - ParameterKey: pGitHubOrganization
          ParameterValue: !Ref pGitHubOrganization
        - ParameterKey: pGitHubRepository
          ParameterValue: !Ref pGitHubRepository
        - ParameterKey: pMaxSessionDuration
          ParameterValue: !Ref pMaxSessionDuration
        - ParameterKey: pSRASolutionName
          ParameterValue: !Ref pSRASolutionName
      Tags:
        - Key: sra-solution
          Value: !Ref pSRASolutionName

Outputs:
  oGitHubOIDCStackName:
    Description: Name of the OIDC Stack
    Value: !Ref rGitHubOIDCStack
    Export:
      Name: !Sub '${AWS::StackName}-GitHubOIDCStackName'

  oGitHubOIDCStackSetName:
    Description: Name of the OIDC StackSet
    Value: !Ref rGitHubOIDCStackSet
    Export:
      Name: !Sub '${AWS::StackName}-GitHubOIDCStackSetName'

  oDeploymentStatus:
    Description: Deployment status information
    Value: !Sub |
      Stack: ${pSRASolutionName}-stack
      StackSet: ${pSRASolutionName}-stackset
      DeploymentType: Organization-wide
      TargetRegion: ${AWS::Region}
    Export:
      Name: !Sub '${AWS::StackName}-DeploymentStatus'
